[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-throttle>=0.1.6",
    "fastapi[standard]>=0.116.1",
]
